[package]
name = "sworkstyle"
version = "1.2.2"
authors = ["Lyr-7D1h <lyr-7d1h@pm.me>"]
edition = "2018"
license = "MIT"
description = "Workspaces with the swayest style! This program will dynamically rename your workspaces to indicate which programs are running in each workspace. It uses the Sway IPC. In the absence of a config file, one will be generated automatically.See ${XDG_CONFIG_HOME}/workstyle/config.yml for  details."
repository = "https://github.com/Lyr-7D1h/swayest_workstyle"
keywords = ["sway", "wayland"]
readme = "README.md"


[dependencies]
swayipc = { version = "2", features = ["async", "event_stream"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
futures-util = "0.3.7"
dirs = "4.0"
log = "0.4"
fslock = "0.2.1"
ctrlc = "3.1.9"
regex = "1.5.4"
anyhow = "1.0.41"
simple_logger = "2.1.0"