# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
#   [exact]
#   "app_name" = "icon"
#
#   [generic]
#   "pattern" = "icon"
#
# You can find "app_name" and "title" in the output of "sworkstyle"
# If it couldn't match something it will print:
# 
# WARN | No match for "app_name" with title "title" 
#
# You can use "title" to match using the "pattern"
#

fallback = 'A'

[matching]
"tmux" = { type = "generic", value = "D" }
"Alacritty" = ""
"Spotify" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""