# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
#   [exact]
#   "app_name" = "icon"
#
#   [generic]
#   "pattern" = "icon"
#
# You can find "app_name" and "title" in the output of "sworkstyle"
# If it couldn't match something it will print:
#
# WARN | No match for "app_name" with title "title"
#
# You can use "title" to match using the "pattern"
#

fallback = ''

[matching]
"github" = { type = "generic", value = "" }
"rust" = { type = "generic", value = "" }
"vim" = { type = "generic", value = "" }
"npm" = { type = "generic", value = "" }
"node" = { type = "generic", value = "" }
"yarn" = { type = "generic", value = "" }
"thunderbird" = ""
"Bitwarden" = ""
"Google-chrome" = ""
"Slack" = ""
"Code" = ""
"Alacritty" = ""
"Spotify" = ""
"firefox" = ""