on: 
  release:
    types: [published]
  
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: publish
        run: cargo publish --verbose

  aur:
    runs-on: ubuntu-latest 
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Checkout aur repo
        run: git clone ssh://aur@aur.archlinux.org/sworkstyle.git
      - name: Update version
        run: sed -i "s/pkgver=.*/pkgver=${{ steps.get_version.outputs.VERSION }}/g" PKGBUILD
      - name: Update srcinfo using makepkg
        uses: edlanglois/pkgbuild-action@v1
      - name: Publish
        run: |
          git add .
          git commit -m "Upgraded to version ${{ steps.get_version.outputs.VERSION }}"
          git push
